### ISSUE TITLE
Promise<void> not working

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#1036]
This isn't working for some reason:

```typescript
import { ic, match, $update } from 'azle';
import { managementCanister } from 'azle/canisters/management';

$update;
export async function test(): Promise<void> {
    const result = await managementCanister
        .install_code({
            mode: {
                upgrade: null
            },
            canister_id: ic.id(),
            wasm_module: Uint8Array.from([]),
            arg: Uint8Array.from([])
        })
        .cycles(100_000_000_000n)
        .call();
    match(result, {
        Ok: () => {
            console.log('it worked');
        },
        Err: () => {
            console.log('it did not work');
        }
    });
}

```

**Comment by dansteren** [comment]
I believe this was caused by https://github.com/demergent-labs/cdk_framework/pull/58.

We used to convert Void into the string `()`, but now it's just the empty string. As a result we generate something that looks like this:

```rust
let reply_value: = js_void_value.try_from_vm() ;
```

So we give a `:` indicating that we're going to provide a type, but then don't because it's now represented as a string.

I believe the solution is as simple as wrapping the returned type in parens. Then void would just be the empty string between the parens, which is just parens.
