### ISSUE TITLE
Create universal equality function

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#1440]
I think we should be able to use deep-equals/fast-equals to create one universal equality checker for all of our values, using something like this code generated by ChatGPT:

```typescript
import { createCustomEqual, deepEqual } from 'fast-equals';

class Principal {
  constructor(private data: any) {}

  toText(): string {
    return String(this.data);
  }
}

const arePrincipalsEqual = (a: any, b: any): boolean => {
  // Check if both a and b are instances of Principal
  if (a instanceof Principal && b instanceof Principal) {
    return a.toText() === b.toText();
  }
  // For non-Principal types, use the default deepEqual
  return deepEqual(a, b);
};

// Create a custom equality checker using fast-equals
const customEqual = createCustomEqual({ '*': arePrincipalsEqual });

// Usage
const obj1 = { name: 'John', principal: new Principal(123) };
const obj2 = { name: 'John', principal: new Principal(123) };
const obj3 = { name: 'Doe', principal: new Principal(456) };

console.log(customEqual(obj1, obj2)); // true
console.log(customEqual(obj1, obj3)); // false

```

**Comment by bdemann** [comment]
fixed with https://github.com/demergent-labs/azle/pull/1442

The problem when we tried to use fast-equals at the beginning was not that Principals were not able to be used with fast-equals but rather that if the Principals were made with different version (or different locations of the same version) of @dfinity/principal then fast-equals wouldn't even consider them and return false before even running them through the custom equals method. Now that we have made sure to use the same version and install location for Principal deepEqual from fast-equals works great out of the box. 

This issue follows the odd behavior of Principal https://github.com/demergent-labs/azle/issues/1443
