### ISSUE TITLE
Document why podman is needed

### ISSUE THREAD

**Issue by fredericrous** [demergent-labs/azle#1670]
Could you please document the reason why podman is required?
I searched in the Azle Book and found just an install step but no explanation https://demergent-labs.github.io/azle/get_started.html?search=podman

Do I really need to get Docker running on my machine to run azle? I mean rust and motoko don't need this. I know Docker's great, I used to do DevOps magic for a living... but it is also inexorably slower than native, and takes up memory and space (substantial space, look at your `~/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw` if you are on mac and have docker desktop.. I'm sure podman has an equivalent).

I think it will help to accept that Azle is using Docker, and maybe one day see it go away with contributions from the community by telling the reason it is there.

I had a look at the https://github.com/demergent-labs/azle/blob/main/src/compiler/Dockerfile
Given the fact `Azle Hello World readme` already asked me to install llvm which is the hard part because it also required me to add `$HOMEBREW/opt/bin/clang` to my path because mac already comes with a clang that does not work with llvm. And given the fact that as an ICP enthusiast, I already have rust on my laptop. And given the fact rust version managers exists https://github.com/javanile/r I don't see the value of using docker and not a script or instructions in a readme... plus I had Docker Desktop already on my mac... but azle made me install podman... I know podman is great... on linux but I have mac and Docker Desktop is good enough for me

My message sure looks like I complain but I didn't chatgpt it :P I just wish to help and communicate honest user feedback
I like what you are doing with Azle, have been following the project for a while and gave it a 2nd try just yesterday to this time try the express demo and hopefully use this in my sass project ^^ first step is I think to document the why podman

**Comment by lastmjs** [comment]
You need to understand the history and complexity of the Azle compiler toolchain and the difficulties of getting that installed across all possible developer machines in possibly poor network conditions.

After multiple rounds in in-person hackathons and many many issues with pulling down the Rust environment and tools required to get Azle to work across all machines, the conclusion was recently made that Docker would be an excellent solution. Docker is relatively complicated to install on Linux at least relative to Podman, and the Podman security model seems defacto better as it is rootless by default.

So we've opted for Podman.

The documentation at the moment, especially in the Getting Started section, is designed to get people started with as little fuss as possible. We've shrunk the "extra" dependencies required down from various sudo apt-gets, llvm on Mac, xcode, to just podman.

So it's been greatly simplified in 0.20.2 to what it just was. We never greatly detailed why each dependency was needed before. I'm not sure we need to now when it's much simpler. Docker/Podman is a required dependency for the build process, which is very complicated and not something we want to expose to the average user of Azle.

And for now Podman is required, we'll see how it goes and perhaps will switch to just Docker if it makes sense, there are trade-offs to these decisions and we must consider all possible dev environments when choosing these technologies, with limited experience, information, etc.

So that's the current state, and I don't plan to necessarily add that specific information into The Azle Book, but happy to answer your questions elsewhere.

The goal is to have as little installation dependencies and information required as possible and present that in the book, a contributors or Azle under-the-hood guide seems more proper for this information, but we don't have that yet and aren't very actively seeking contributions for the deep under-the-hood work that we do full-time in close collaboration as a team.

**Comment by fredericrous** [comment]
Thanks for the detailed reply @lastmjs Indeed I see now with 0.20.2 the install is simpler

**Comment by lastmjs** [comment]
Good news, Podman is no longer needed and the installation process is now much much better.
