### ISSUE TITLE
Implement null type

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#200]
I do not think we have full support for the null type, just Opt: https://smartcontracts.org/docs/candid-guide/candid-types.html#type-null

- [x] Candid
- [x] AzleIntoJsValue
- [x] AzleFromJsValue

Out of scope: handling null values in crazy places like inside of records and variants. Those aren't as high a priority so we will wait until someone reports an issue with those and fix them at that time.

**Comment by dansteren** [comment]
In order to determine if this was a problem with Azle or Rust, Jordan and I created the equivalent canister in raw rust. Namely, one having the following lib.rs file:
```rust
#[ic_cdk_macros::query]
fn get_null() -> () {
    return ();
}
```
This has the same candid signature as our azle canister. When testing this raw rust canister with the JS Agent we got the same error message: `Wrong number of return values`. We therefore concluded this was an issue with the JS Agent implementation and opened https://github.com/dfinity/agent-js/issues/581.

As such, I'm proceeding with this issue under the assumption that the rust code we're generating is correct and will just not use the JS agent in tests until that issue is resolved.
