### ISSUE TITLE
Use _azle_ prefix for all variables where user-generated code may mix

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#242]
We need to be very careful when the user's code will be mixed with azle's. Make sure to also check the CDK Framework as well.

**Comment by lastmjs** [comment]
Related: https://github.com/demergent-labs/azle/issues/347

**Comment by dansteren** [comment]
Update for today. I've [changed the API](https://github.com/demergent-labs/cdk_framework/commit/fcee33ffe2b66a3e744ba9a3c8e0f7fa4377c8ba) for CDK Framework of how we call the wrapper functions. I grouped all the user-defined params together so that the names wouldn't clash.

My next steps include:

- [ ] Update kybra to match the new API
- [ ] Prefix all user-defined params in canister methods. This will help if they use Rust keywords. Note: Somehow I already did this in Kybra but I think I did it at the wrong layer so I'm analyzing this now.
