### ISSUE TITLE
Prefix everything to prevent clashes with user-defined items

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#941]
Places where name clashes can occur:
- **canister method parameter names and record/variant members/properties.** We use these raw names for the variables in our code. These can clash with other variables that we make (like `boa_context`) or with rust keywords. For the most part he have this handled. Our solution is to prefix everything with `cdk_user_defined_`. This makes rust keyword clashes impossible and should be easy to avoid clashes with our stuff. So the only thing to do here is to make sure we've actually done this everywhere.
- **canister method and guard function names.** These can clash with existing global function names such as `_cdk_get_candid_pointer`. We've tried to prefix all of our stuff with `_azle_` and `_cdk_`. This greatly limits the clashes. So, we should at least make sure that there aren't any more global functions that aren't prefixed. To make this even better though, we would either move all user-defined methods/functions into a module, or all of our stuff into a module. Both could work, but they need to be separated. Any time we use our stuff in the user-defined scope we need to make sure to always use a fully qualified name. That way we can never have clashes here. However, there could still be problems if their function name is a rust keyword. So we need to handle that.
- **user defined types.** These can conflict with globally available rust types (like `Result`) or types that we've imported with `use` statements (like `CandidType`, or `CdkActTryIntoVmValue`, or `Clone`). Because blurring of our types and their types is guaranteed, the only sure-fire way to avoid this is to namespace-qualify all our types within the user-defined scope/module. Becuase **all** of our types would need this, there is a very strong case for moving all user-defined types into a `user_defined` module. A benefit is that outside that module, we wouldn't need to fully namespace qualify some types which would improve the readability of our rust code.

Therefore, the way to solve this ticket will involve a combination of using modules to group areas of code, and namespace-qualifying imports so that they cannot clash.

Note: we were running into this in the audio_recorder example because we tried to create a `Key` type, but that clashes with `use slotmap::Key`.

With all that in mind, tasks left to accomplish include:

- [x] Prove that candid file generation will work even if the methods/types are nested in a module. (It's very complicated)
- [x] ~Create a `user_defined` module and put all user-defined types and canister methods in there.~ Decided not to do this for now since this gets very complicated.
- [x] Remove any use statements in favor of qualifying those types with the module name. This makes the path longer and more repetitive (Note: this only needs to happen in the `user_defined` module.
- [x] ~Prefix types that we create. E.g. `type Memory = VirtualMemory` should be `type _AzleMemory = VirtualMemory`~ (use namespaces instead)
- [x] Make sure that all user-defined variable names are correctly prefixed with `cdk_user_defined`.
- [x] ~Somehow prevent clashes between user-defined types and types that get pulled in automatically because of an import they use. E.g. if the user uses the management canister then they automatically get a `Satoshi` type and they can no longer use it.~ Offloaded to [future epic](https://github.com/demergent-labs/azle#workspaces/engineering-63eff82fd9fe250011f32225/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTI4Mjcw).
- [ ] Make sure user-defined records/enums/types/etc don't clash with rust keywords. We currently only handle methods
- [ ] Make a keywords example (borrowing from kybra) and expand it to test the last bullet point.

**Comment by dansteren** [comment]
After most of the work I've done to scope things to specific modules, I'm currently getting problems with the implementation in the following examples:

## Composite Queries
Inside of the ic_object module we need to refer to types out at the crate level. But, if it's a primitive we don't want to prefix it with "crate". So we need to be able to distinguish between user-defined types and our own types.

Attempted solution: move prefixing into `to_type_annotation` instead of doing it at the prefix level`.

## Cross Canister Calls
In service functions (call_canister_method_wrapper) we need to know the datatype of the user-defined variables. We currently just stick "crate::" in front of everything. This doesn't work for built-in types like String or u64. We need to only put these on for user-defined types.

## Manual Reply
Inside the ic_object's reply function we need our types to be crate::SomeUserDefinedType, or candid::Reserved, or String (no prefix for builtin types)

## Outgoing HTTP Response
We need to prefix user-defined types with `crate::` ... but not built-in types. This is also in ic_object's reply function.

## Rejections
Problem in `call_SomeService_reject_wrapper`. again, need to put the type of the user-defined variables. `crate::String` isn't working. So we need to better know if we need to put the `crate::` prefix on or not.

**Comment by dansteren** [comment]
We've decided to abandon the modularization path for the time being. There were just too many issues with it. I've created [an Epic](https://github.com/demergent-labs/azle#workspaces/engineering-63eff82fd9fe250011f32225/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTI4Mjcw) to attempt it again in the future.

For now we'll just use prefixes and remove `use` statements.

**Comment by dansteren** [comment]
We are unable to prefix user-defined methods because of an issue in candid. See https://github.com/demergent-labs/cdk_framework/issues/66
